class ConfigConstants(object):
    ALLOW_COOKIES = 'allow_cookies'
    CONFIG_FILE = 'config_file'
    DELAY = 'delay'
    FILTER = 'Filter'
    FILTER_RULE = 'Rule'
    HEADER = 'header'
    HOST = 'host'
    LOG_FORMAT = 'log_format'
    LOGFILE = 'log_file'
    METHODS = 'Methods'
    RAMP_UP = 'ramp_up'
    STATUS = 'Status'
    TIMED = 'timed'
    TRANSFORM = 'transform'
    VERBOSE = 'verbose'
    WORKER_COUNT = 'worker_count'
